apiVersion: v1
kind: Pod
metadata:
  name: jornada-milhas
  labels:
    app: jornada-milhas
spec:
  containers:
  - name: jornada-milhas
    image: jornada-milhas-vue:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
