export const DESTINATION_POST = 'DESTINATION_POST'
export const DESTINATION_ALL_GET = "DESTINATION_ALL_GET"
export const DESTINATION_GET_BY_ID = "DESTINATION_GET_BY_ID"
export const DESTINATION_PUT_UPDATE = "DESTINATION_PUT_UPDATE"
export const DESTINATION_DELETE_BY_ID = "DESTINATION_DELETE_BY_ID"